<a href="https://colab.research.google.com/github/OwenGeeAndre/DataScience_MachineLearning/blob/main/2_Feature_Selection_Standardization.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Feature Selection - Standardization

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
sns.set()

from sklearn.linear_model import LinearRegression

## Load the Data

In [5]:
df = pd.read_csv(r'/content/1.02.+Multiple+linear+regression.csv')
df.head(2)

SAT  Rand 1,2,3   GPA
0  1714           1  2.40
1  1664           3  2.52

# Multiple Linear Regression

## Independent and Dependent Variables


In [6]:
target = "GPA"
x = df.drop(columns=target)
y = df[target]

In [11]:
x.head(3)

SAT  Rand 1,2,3
0  1714           1
1  1664           3
2  1760           3

## Standardization

In [8]:
from sklearn.preprocessing import StandardScaler

In [9]:
scaler = StandardScaler()

In [10]:
scaler.fit(x)

StandardScaler()

In [12]:
x_scaled = scaler.transform(x)

# Regression with Scaled Features

In [14]:
reg = LinearRegression()
reg.fit(x_scaled, y)

LinearRegression()

In [15]:
reg.coef_

array([ 0.17181389, -0.00703007])

In [16]:
reg.intercept_

np.float64(3.330238095238095)

# Creating a Summary Table

In [19]:
reg_summary = pd.DataFrame([["Bias"],["SAT"],["Rand 1,2,3"]], columns =["Features"])
reg_summary["Weights"] = reg.intercept_, reg.coef_[0], reg.coef_[1]

In [20]:
reg_summary

Features   Weights
0        Bias  3.330238
1         SAT  0.171814
2  Rand 1,2,3 -0.007030



```
For a scaled data: The closer a weight is to O, the smaller its impact;
The bigger the weight, the bigger its impact
```



# Making Predictions (with standardized weights)

In [22]:
new_data = pd.DataFrame(data=[[2100,2],[1500,1]], columns=["SAT", "Rand 1,2,3"])
new_data

SAT  Rand 1,2,3
0  2100           2
1  1500           1

In [23]:
reg.predict(new_data)

/usr/local/lib/python3.12/dist-packages/sklearn/utils/validation.py:2732: UserWarning: X has feature names, but LinearRegression was fitted without feature names
  warnings.warn(


array([364.12535273, 261.04404715])

> The input data has to be in the same form as the data used to train the model

In [24]:
new_data_scaled = scaler.transform(new_data)
new_data_scaled

array([[ 2.45149212, -0.07002087],
       [-3.32292498, -1.24637147]])

In [25]:
reg.predict(new_data_scaled)

array([3.75193075, 2.76807549])

# Modelling (without `Rand 1,2,3`)

In [26]:
new_reg = LinearRegression()
x_simple = x_scaled[:,0].reshape(-1,1)
new_reg.fit(x_simple, y)

LinearRegression()

In [27]:
new_reg.predict(new_data_scaled[:,0].reshape(-1,1))

array([3.7519852 , 2.75857237])

> When we apply feature scaling, it does not affect the final result if we keep or leave out insiginificant variables
