<a href="https://colab.research.google.com/github/OwenGeeAndre/DataScience_MachineLearning/blob/main/3_Train_Test_Split.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Train Test Split

In [7]:
import numpy as np
from sklearn.model_selection import train_test_split

# Generating data

In [8]:
a = np.arange(1,101)
b = np.arange(501,601)

In [9]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [10]:
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

# Splitting Data

In [14]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size=0.2)

> by default, tts splits 75:25
>
> random_state keeps the splits from changing each time we run
>


In [12]:
a_train

array([ 62,  80,  86,  74,  96,  89,  39,  60,  56,  10,  66,  81,   5,
        33,  30,  50,  67,  22,  98,  91,  16,  70,  59,  92,  34,  17,
        44,   9,  47,  37,  41,  85,  15,  35,  21, 100,  79,  54,  97,
        26,  63,  88,  40,  19,  46,  25,  61,  78,   6,  76,   8,  13,
        45,  73,  68,  24,  69,  38,   2,  75,   1,  99,  11,  23,  65,
        72,  53,  93,  18,   4,  55,  14,  12,  27,  48,  49,  84,  51,
         3,  36])

In [13]:
a_test

array([20, 82, 77, 83, 64, 95, 71, 57, 58, 29, 28, 90, 32, 52, 42, 87,  7,
       94, 43, 31])

In [15]:
b_train

array([599, 551, 505, 532, 595, 596, 593, 577, 569, 515, 556, 507, 576,
       521, 547, 584, 559, 566, 600, 516, 567, 574, 513, 522, 578, 503,
       597, 537, 585, 586, 561, 533, 546, 542, 525, 512, 564, 517, 510,
       514, 582, 552, 526, 541, 519, 502, 524, 554, 573, 565, 518, 511,
       568, 529, 504, 594, 520, 589, 592, 558, 501, 575, 509, 535, 545,
       588, 587, 590, 581, 530, 571, 563, 579, 528, 540, 562, 591, 550,
       506, 508])

In [16]:
b_test

array([557, 555, 560, 570, 580, 583, 553, 531, 572, 536, 539, 598, 523,
       543, 538, 527, 544, 549, 534, 548])